### ISSUE TITLE
Postscript file generates AprilTags with black and white reversed

### ISSUE THREAD

**Issue by cynosure4sure** [AprilRobotics/apriltag-imgs#1]
I saw a recent commit which corrected png files as they had black/white bits reversed. I think the provided postscript files still generate tags with black/white bits reversed.

The postscript files from commit 83144708e80a08890246d67d1ac661ff49ae96c5 have the correct order of bits for tag generation.

**Comment by mkrogius** [comment]
Fixed in #64a553eeb9872944abfd4ad9258a644aded973fa

Thanks
